import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { GoogleTagManager } from "@next/third-parties/google";

import "./globals.css";

import { MainHeader } from "@/features/shared/ui/MainHeader";
import { BannerBox } from "@/features/shared/ui/boxes/BannerBox";
import { MainFooter } from "@/features/shared/ui/MainFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <GoogleTagManager gtmId="GTM-MZ5B7LWK" />
      <body
        className={`flex flex-col h-full ${geistSans.variable} ${geistMono.variable} font-geist-sans antialiased`}
      >
        <div className="flex flex-col flex-1 w-full bg-primary-bg">
          <div className="flex flex-row justify-center mb-28">
            <div className="flex flex-col box-border w-full px-4 md:px-8 lg:w-5xl">
              <MainHeader />
              <BannerBox className="mt-8" />
              <main>
                <article>{children}</article>
              </main>
            </div>
          </div>
        </div>
        <MainFooter />
      </body>
    </html>
  );
}
